import jsPDF from "jspdf"
import autoTable from "jspdf-autotable"
import "jspdf-autotable"

interface PdfReportInput {
  siteName: string
  siteAddress: string
  periodLabel: string
  usage: { electricity: number; gas: number; water: number }
  costs: { electricity: number; gas: number; water: number } | null
  dailyBreakdown: Array<{ date: string; electricity: number; gas: number; water: number }>
}

type AutoTableStateDoc = jsPDF & {
  lastAutoTable?: { finalY: number }
}

const usageFormatter = new Intl.NumberFormat("en-US", {
  maximumFractionDigits: 2,
})

const costFormatter = new Intl.NumberFormat("en-US", {
  maximumFractionDigits: 0,
})

function formatUsage(value: number): string {
  return usageFormatter.format(value)
}

function formatCost(value: number): string {
  return costFormatter.format(value)
}

export function generateReportPdf(input: PdfReportInput): ArrayBuffer {
  const doc = new jsPDF({ unit: "pt", format: "a4" })
  const autoTableStateDoc = doc as AutoTableStateDoc
  const marginX = 40
  const pageHeight = doc.internal.pageSize.getHeight()
  let cursorY = 56

  doc.setFont("helvetica", "bold")
  doc.setFontSize(20)
  doc.text("EnergyGuard Monthly Report", marginX, cursorY)

  doc.setFont("helvetica", "normal")
  doc.setFontSize(11)
  cursorY += 26
  doc.text(`Site: ${input.siteName}`, marginX, cursorY)
  cursorY += 16
  doc.text(`Address: ${input.siteAddress}`, marginX, cursorY)
  cursorY += 16
  doc.text(`Period: ${input.periodLabel}`, marginX, cursorY)

  const summaryRows = [
    [
      "Electricity",
      formatUsage(input.usage.electricity),
      "kWh",
      input.costs ? formatCost(input.costs.electricity) : "-",
    ],
    [
      "Gas",
      formatUsage(input.usage.gas),
      "m3",
      input.costs ? formatCost(input.costs.gas) : "-",
    ],
    [
      "Water",
      formatUsage(input.usage.water),
      "ton",
      input.costs ? formatCost(input.costs.water) : "-",
    ],
  ]

  cursorY += 28
  doc.setFont("helvetica", "bold")
  doc.setFontSize(13)
  doc.text("Summary", marginX, cursorY)

  autoTable(doc, {
    startY: cursorY + 10,
    margin: { left: marginX, right: marginX },
    head: [["Energy Type", "Usage", "Unit", "Cost (KRW)"]],
    body: summaryRows,
    theme: "grid",
    styles: {
      font: "helvetica",
      fontSize: 10,
      cellPadding: 6,
    },
    headStyles: {
      fillColor: [31, 41, 55],
      textColor: 255,
      fontStyle: "bold",
    },
  })

  const summaryEndY = autoTableStateDoc.lastAutoTable?.finalY ?? cursorY + 84
  const dailyRows = input.dailyBreakdown.map((daily) => [
    daily.date,
    formatUsage(daily.electricity),
    formatUsage(daily.gas),
    formatUsage(daily.water),
  ])

  doc.setFont("helvetica", "bold")
  doc.setFontSize(13)
  doc.text("Daily Breakdown", marginX, summaryEndY + 26)

  autoTable(doc, {
    startY: summaryEndY + 36,
    margin: { left: marginX, right: marginX },
    head: [["Date", "Electricity (kWh)", "Gas (m3)", "Water (ton)"]],
    body: dailyRows,
    theme: "grid",
    styles: {
      font: "helvetica",
      fontSize: 9,
      cellPadding: 5,
    },
    headStyles: {
      fillColor: [31, 41, 55],
      textColor: 255,
      fontStyle: "bold",
    },
  })

  const generatedDate = new Intl.DateTimeFormat("en-US", {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(new Date())

  doc.setTextColor(99, 99, 99)
  doc.setFont("helvetica", "normal")
  doc.setFontSize(10)
  doc.text("Generated by EnergyGuard", marginX, pageHeight - 28)
  doc.text(`Generated on: ${generatedDate}`, marginX, pageHeight - 14)

  return doc.output("arraybuffer")
}
